# -*- coding: utf-8 -*-
"""MC segundo o PE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsX0qwwRBBtDixAVrxxsqFK9iqoeYAxd

# Parte Determinística

## Método de Euler

O método de Euler consiste em encontrar os valores de uma EDO de ordem 1 através de análises numéricas

Para isso, utiliza-se a seguinte equação

y$_{k + 1}$ = y$_k$ + hy'$_k$

Onde:

k é o termo que indica o número de soluções encontradas

h é o número de passos que irá dar

y' é a derivada da função
"""

import math
import numpy as np
vet1 = []
vet2 = []

h = 0.1
x_inicial = 1
y_inicial = 1
x_final = 1.5
def fun(x,y):
  return (2/10)*x*y

for i in range(10):
  x = x_inicial + i * h

  y = y_inicial + h * fun(x, y_inicial)
  vet1.append(y)
  y_inicial = y

  vet2.append(round(x,3))

print(vet2)
print(vet1)

import pandas as pd

lin = [vet2]
col = ['Xn', 'Valores']
date = [vet1]
df = pd.DataFrame(vet1, columns = ['Valores'])

df['Xn'] = vet2

df.set_index('Xn', inplace=True)

df

"""# Método do Trapézio

O método do trapézio consiste em pegar uma função e dividi-lá em diversos trapézios, onde, através da soma das áreas de todos os trapézios, chegará numa aproximação do valor exato da integral

$\int_{a}^{b}f(x)dx $ ≈ $\frac{h}{2}$$[f_{inicial} + 2(\sum f_{meio}) + f_{final}]$

Onde:

h = $\frac{b - a}{n}$

Sendo "n" o número de divisões
"""

import math
import numpy as np
cont = 0
vet1 = []
vet2 = []
vet3 = []


a = 1
b = 3
n = 5

h = (b - a)/n

mei_d = a + h
c = n

def fun(x):
  return exp(-(x**2))

for i in range(1,c):
  x = a + i * h
  func = fun(x)

  vet2.append(round(func,5))
  sum = np.sum(vet2)

print(sum)
area = (h/2)*(fun(a) + 2 * sum + fun(b))

vet1.append(round(fun(a),5))
vet3.append(round(fun(b),5))

print(vet1)
print(vet2)
print(vet3)
print(round(area,10))

import pandas as pd

col = ['Início', 'Fim', 'Intervalo', 'Valor da função inicial','Valor da soma das frações do meio', 'Valor da função final', 'Área da integral']
date = [[a, b, h, vet1, vet2, vet3, area]]

df = pd.DataFrame(date, columns = col)

df

"""# Método do Simpson"""

